[tool.poetry]
name = "groningen-waste-collection"
version = "0.1.0"
description = ""
authors = ["Niels Wouda <nielswouda@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^1.4.2"
numpy = "^1.22.3"
openpyxl = "^3.0.9"
matplotlib = "^3.5.1"
requests = "^2.27.1"
Pillow = "^9.1.0"
jupyter = "^1.0.0"
ipython-sql = "^0.4.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
